// Generated by CoffeeScript 1.6.3
(function() {
  var add, arg, nums, _i, _len, _ref;

  add = function(nums) {
    var n, result, _i, _len;
    result = 0;
    for (_i = 0, _len = nums.length; _i < _len; _i++) {
      n = nums[_i];
      result += n;
    }
    return result;
  };

  nums = [];

  _ref = process.argv.slice(2);
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    arg = _ref[_i];
    arg = Number(arg);
    nums.push(arg);
  }

  console.log(add(nums));

}).call(this);
