// Generated by CoffeeScript 1.6.3
(function() {
  var fs, read, target;

  fs = require('fs');

  read = function(stream) {
    var buffer, contents;
    buffer = fs.readFileSync(stream);
    contents = buffer.toString();
    return contents;
  };

  target = read(process.argv[2]);

  target = target.split("\n");

  console.log(target.length - 1);

}).call(this);
